name: shingtest
favicon: null
layout_spectrum: 0.87396
typography_spectrum: 0.86227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e1414'
    - '#8e6e45'
    - '#ffffff'
    - '#a3b4bc'
    - '#618cb7'
  brandStrength: 0.8125
  lightness: 0.9190753372386098
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
