name: shingtest
favicon: null
layout_spectrum: 0.91402
typography_spectrum: 0.63689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040807'
    - '#1f2324'
    - '#cdcfce'
    - '#3e3e34'
    - '#8c8e8d'
  brandStrength: 0.0625
  lightness: 0.9190753372386098
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
